import os, json, time, sys
import pandas as pd
from confluent_kafka import Producer

def main():
    print("=" * 60)
    print("VaultMind 3.0 - Live Kafka Producer (Dynamic Demo)")
    print("=" * 60)
    
    # Path to the dataset generated by data_generator_v2.py
    csv_path = os.path.join(os.path.dirname(__file__), "scripts", "Testing_data", "live_demo_stream.csv")
    if not os.path.exists(csv_path):
        print(f"ERROR: Could not find {csv_path}")
        return

    print("Connecting to Kafka broker at localhost:9092...")
    try:
        producer = Producer({
            'bootstrap.servers': os.getenv('KAFKA_BROKER', 'localhost:9092')
        })
    except Exception as e:
        print(f"FATAL: Could not connect to Kafka broker. Make sure Kafka is running!\n{e}")
        return

    print(f"Loading {csv_path}...")
    df = pd.read_csv(csv_path)
    print(f"Loaded {len(df)} transactions. Starting live stream...")
    
    for idx, row in df.iterrows():
        tx = row.where(pd.notnull(row), None).to_dict()
        try:
            producer.produce('live-transactions', value=json.dumps(tx).encode('utf-8'))
            producer.flush()
            tag = "FRAUD" if tx.get("is_fraud_flag") == 1 else "NORMAL"
            print(f"Produced [{tag}]: {tx.get('transaction_id')} (Row {idx+1})")
        except Exception as e:
            print(f"Error producing transaction: {e}")
        time.sleep(2)  # Stream 1 transaction every 2 seconds

if __name__ == "__main__":
    main()
